apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: cncf-pune-k3d-demo
servers: 1
agents: 0
kubeAPI:
  host: "0.0.0.0"
  hostIP: "127.0.0.1"
  hostPort: "6443"
ports:
  - port: 8080:8080
    nodeFilters:
      - loadbalancer
  - port: 80:80
    nodeFilters:
      - loadbalancer
  - port: 443:443
    nodeFilters:
      - loadbalancer