apiVersion: apps/v1
kind: Deployment
metadata:
  name: cncf-pune-demo
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cncf-pune-demo
  template:
    metadata:
      labels:
        app: cncf-pune-demo
    spec:
      containers:
      - name: nginx
        image: cncf-pune-demo:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: cncf-pune-demo
  namespace: demo
spec:
  selector:
    app: cncf-pune-demo-notexists
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP